# Base image for JetPack 5, image that is compatible with EVI devices jetpack
FROM nvcr.io/nvidia/l4t-base:35.4.1 AS builder

RUN apt-get update && apt-get install -y --no-install-recommends \
    python3-pip \
    libjpeg-dev \
    libopenblas-dev \
    libomp-dev \
    ffmpeg \
    musl \
    gcc \
    cargo \
    nginx \
    python3-opencv \
    && rm -rf /var/lib/apt/lists/*

# Add NVIDIA’s APT repo for JetPack 5.1.2

# Install ultralytics with minimal dependencies
RUN pip3 install --prefix=/build --no-cache-dir \
    'packaging>=23.2,<24.0' \
    ultralytics==8.3.175 \
    flask==2.3.3 \
    flask-socketio==5.3.6 \
    eventlet==0.33.3 \
    numpy==1.24.4 \
    uvicorn==0.33.0 \
    openai==1.10.0 \
    langchain==0.1.16 \ 
    langchain_openai==0.0.8 \
    langchain_community==0.0.34 \
    pypdf==3.17.4 \
    fastapi==0.116.1 \
    torchvision==0.15 \
    rapidfuzz==3.6.1 \
    reportlab==4.1.0

RUN pip3 uninstall torch
RUN apt-get update && apt-get install -y wget && \
    wget -O torch-2.0.0a0_nv23.03-cp38-cp38-linux_aarch64.whl "https://developer.download.nvidia.com/compute/redist/jp/v51/pytorch/torch-2.0.0a0%2B8aa34602.nv23.03-cp38-cp38-linux_aarch64.whl" && \
    pip3 install --prefix=/build --no-cache-dir torch-2.0.0a0_nv23.03-cp38-cp38-linux_aarch64.whl

RUN find /build -name '*.pyc' -delete && \
    find /build -type d -name '__pycache__' -exec rm -r {} + && \
    rm -rf /build/**/*.dist-info

FROM nvcr.io/nvidia/l4t-base:35.4.1

RUN apt-get update && apt-get install -y --no-install-recommends \
    gnupg2 curl ca-certificates && \
    curl -fsSL https://repo.download.nvidia.com/jetson/jetson-ota-public.asc | apt-key add - && \
    echo "deb https://repo.download.nvidia.com/jetson/common r35.4 main" > /etc/apt/sources.list.d/nvidia-l4t.list && \
    echo "deb https://repo.download.nvidia.com/jetson/t234 r35.4 main" >> /etc/apt/sources.list.d/nvidia-l4t.list

# Install essential dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
    python3-pip \
    libjpeg-dev \
    libopenblas-dev \
    libomp-dev \
    ffmpeg \
    musl \
    nginx \
    python3-opencv \
    cuda-cudart-11-4 \
    libcudnn8 \
    libnvinfer8 \
    libnvonnxparsers8 \
    libnvparsers8 \
    libnvinfer-plugin8 \
    libcusparse-11-4 \
    cuda-nvtx-11-4 \
    libcufft-11-4 \
    libcurand-11-4 \
    && rm -rf /var/lib/apt/lists/*

ENV PYTHONPATH="/usr/local/lib/python3.8/site-packages:${PYTHONPATH}"
COPY --from=builder /build /usr/local
