# Base image for JetPack 5, image that is compatible with EVI devices jetpack
FROM nvcr.io/nvidia/l4t-pytorch:r35.4.1-pth2.0-py3

RUN apt-get update && apt-get install -y --no-install-recommends \
    python3-pip \
    libjpeg-dev \
    libopenblas-dev \
    libomp-dev \
    ffmpeg \
    musl \
    gcc \
    cargo \
    nginx \
    python3-opencv \
    && rm -rf /var/lib/apt/lists/*

# Install ultralytics with minimal dependencies
RUN pip3 install --no-cache-dir \
    'packaging>=23.2,<24.0' \
    ultralytics==8.2.0 \
    flask==2.3.3 \
    flask-socketio==5.3.6 \
    eventlet==0.33.3 \
    numpy==1.24.4 \
    openai==1.10.0 \
    langchain==0.1.16 \ 
    langchain_openai==0.0.8 \
    langchain_community==0.0.34 \
    pypdf==3.17.4 \
    rapidfuzz==3.6.1 \
    reportlab==4.1.0

