FROM nvidia/cuda:12.3.2-runtime-ubuntu22.04

# Install essential dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
    python3-pip \
    libjpeg-dev \
    libopenblas-dev \
    libomp-dev \
    ffmpeg \
    musl \
    gcc \
    cargo \
    nginx \
    && rm -rf /var/lib/apt/lists/*

RUN pip3 install torch==2.1.2+cu123 torchvision==0.16.2+cu123 --extra-index-url https://download.pytorch.org/whl/cu123

# Install ultralytics with minimal dependencies
RUN pip3 install --no-cache-dir \
    ultralytics \
    flask \
    flask-socketio \
    eventlet \
    opencv-python-headless \
    numpy \
    openai \
    langchain \ 
    langchain_openai \
    langchain_community \
    pypdf \
    rapidfuzz \
    reportlab

