# Base image for JetPack 5, image that is compatible with EVI devices jetpack
FROM nvcr.io/nvidia/l4t-base:35.4.1

# Install essential dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
    python3-pip \
    libjpeg-dev \
    libopenblas-dev \
    libomp-dev \
    ffmpeg \
    musl \
    gcc \
    cargo \
    nginx \
    python3-opencv \
    && rm -rf /var/lib/apt/lists/*

# Install cuda libraries

# Add NVIDIA’s APT repo for JetPack 5.1.2
RUN apt-get update && apt-get install -y --no-install-recommends \
    gnupg2 curl ca-certificates && \
    curl -fsSL https://repo.download.nvidia.com/jetson/jetson-ota-public.asc | apt-key add - && \
    echo "deb https://repo.download.nvidia.com/jetson/common r35.4 main" > /etc/apt/sources.list.d/nvidia-l4t.list && \
    echo "deb https://repo.download.nvidia.com/jetson/t234 r35.4 main" >> /etc/apt/sources.list.d/nvidia-l4t.list

# Install runtime CUDA libraries only (minimal)
RUN apt-get update && apt-get install -y --no-install-recommends \
    cuda-cudart-11-4 \
    libcudnn8 \
    libnvinfer8 \
    libnvonnxparsers8 \
    libnvparsers8 \
    libnvinfer-plugin8 \
    libcusparse-11-4 \
    cuda-nvtx-11-4 \
    libcufft-11-4 \
    libcurand-11-4
 
# Install ultralytics with minimal dependencies
RUN pip3 install --no-cache-dir \
    'packaging>=23.2,<24.0' \
    ultralytics==8.2.0 \
    flask==2.3.3 \
    flask-socketio==5.3.6 \
    eventlet==0.33.3 \
    numpy==1.24.4 \
    openai==1.10.0 \
    langchain==0.1.16 \ 
    langchain_openai==0.0.8 \
    langchain_community==0.0.34 \
    pypdf==3.17.4 \
    rapidfuzz==3.6.1 \
    reportlab==4.1.0

RUN apt-get update && apt-get install -y wget && \
    wget "https://developer.download.nvidia.com/compute/redist/jp/v51/pytorch/torch-2.0.0a0%2B8aa34602.nv23.03-cp38-cp38-linux_aarch64.whl" && \
    pip3 install --no-cache-dir torch-2.0.0a0+8aa34602.nv23.03-cp38-cp38-linux_aarch64.whl && \
    rm torch-2.0.0a0+8aa34602.nv23.03-cp38-cp38-linux_aarch64.whl

