FROM nvidia/cuda:12.9.0-cudnn-runtime-ubuntu24.04

# Install essential dependencies
RUN apt-get update && apt-get install -y --no-install-recommends \
    python3-venv \
    libjpeg-dev \
    ffmpeg \
    musl \
    gcc \
    cargo \
    nginx \
    && rm -rf /var/lib/apt/lists/*

# Create and activate a virtual environment
RUN python3 -m venv /opt/venv
ENV PATH="/opt/venv/bin:$PATH"

RUN pip3 install torch torchvision --extra-index-url https://download.pytorch.org/whl/cu129

# Install ultralytics with minimal dependencies
RUN pip3 install --no-cache-dir \
    ultralytics \
    flask \
    flask-socketio \
    eventlet \
    opencv-python-headless \
    numpy \
    openai \
    langchain \ 
    langchain_openai \
    langchain_community \
    pypdf \
    rapidfuzz \
    reportlab \
    fastapi \
    uvicorn \
    starlette \
    websockets \
    pydantic \
    pydantic_core \
    annotated-types \
    torch==2.7.0 \
    torchvision \
    ultralytics \
    ultralytics-thop \
    opencv-python \
    pillow \
    scikit-image \
    requests \
    typing_extensions
