name: Build Docker Image check

on:
  pull_request:
    branches:
      - main  
      - prod

env:
  environment: ${{ github.ref == 'refs/heads/prod' && 'prod' || 'staging' }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build and Tag Docker Image
        run: |
          docker build --build-arg BUILD_ENVIRONMENT=${{env.environment}} -t $(basename ${{ github.repository }}):${{github.sha}} .

