name: Build and Push Docker base runtime image for Jetson devices and Nvidia cloud nodes

on:
  workflow_dispatch:
    inputs:
      image_type:
        description: "Image type"
        required: true
        default: "jetson"
        type: choice
        options:
          - nvidia
          - jetson
      arch:
        description: "Target architecture"
        required: true
        default: "ARM64"
        type: choice
        options:
          - X64
          - ARM64

jobs:
  build-and-push:
    runs-on: [self-hosted, "${{github.event.inputs.arch}}"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Scaleway Container Registry
        run: |
          echo "CONTAINER_PATH=rg.${{ secrets.SCW_REGION }}.scw.cloud/${{secrets.SCW_NAMESPACE}}/${{github.event.inputs.image_type}}_base:${{github.sha}}" >> $GITHUB_ENV
          echo "CONTAINER_LATEST_PATH=rg.${{ secrets.SCW_REGION }}.scw.cloud/${{secrets.SCW_NAMESPACE}}/${{github.event.inputs.image_type}}_base:latest" >> $GITHUB_ENV
          echo ${{secrets.SCW_SECRET_KEY}} | docker login rg.${{secrets.SCW_REGION}}.scw.cloud -u ${{secrets.SCW_ACCESS_KEY}} --password-stdin

      - name: Build and Tag Docker Image
        run: |
          docker build -t $CONTAINER_PATH -f Dockerfile.${{github.event.inputs.image_type}}  .

      - name: Push Docker Image to Docker Hub for main branch
        run: |
          docker push $CONTAINER_PATH
          docker tag $CONTAINER_PATH $CONTAINER_LATEST_PATH
          docker push $CONTAINER_LATEST_PATH


