name: Build and Push Docker Image

on:
  workflow_call:
    inputs:
      buildtype:
        required: false
        type: string
        default: "cloud"
      arch:
        type: choice
        options:
          - X64
          - ARM64
        required: false
        default: X64

env:
  buildtype: ${{inputs.buildtype}}

jobs:
  build-and-push:
    runs-on: [self-hosted, "${{ input.arch }}"]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to Scaleway Container Registry
        run: |
          REPO_NAME="$(basename ${{ github.repository }})"
          echo "CONTAINER_PATH=rg.${{ secrets.SCW_REGION }}.scw.cloud/${{secrets.SCW_NAMESPACE}}/${REPO_NAME}-${{env.buildtype}}:${{github.sha}}" >> $GITHUB_ENV
          echo "REPO_NAME=${REPO_NAME}" >> $GITHUB_ENV
          echo ${{secrets.SCW_SECRET_KEY}} | docker login rg.${{secrets.SCW_REGION}}.scw.cloud -u ${{secrets.SCW_ACCESS_KEY}} --password-stdin

      - name: Build and Tag Docker Image
        run: |
          docker build --build-arg CONFIGURATION_TYPE=${{env.buildtype}} -t $CONTAINER_PATH -f Dockerfile.${{env.buildtype}}  .

      - name: Push Docker Image to Docker Hub for main branch
        run: |
          docker push $CONTAINER_PATH

      - name: Checkout deployed configuration
        uses: actions/checkout@v3
        with:
          repository: incidentware/kubeconfigs
          ref: main
          path: kubeconfigs
          token: ${{ secrets.ORG_REPO_ROBOT_SECRET }}

      - name: Deploy container
        run: |
          GH_TOKEN=${{ secrets.ORG_REPO_ROBOT_SECRET }}
          cd $GITHUB_WORKSPACE/kubeconfigs
          [ "${{env.buildtype}}" = "cloud" ] && ENVIRONMENT="staging" || ENVIRONMENT="${{env.buildtype}}"
          git config user.name "${{secrets.ORG_REPO_ROBOT_USERNAME}}"
          git config user.email "${{secrets.ORG_REPO_ROBOT_EMAIL}}"
          python3 update.py --environment $ENVIRONMENT --service ${REPO_NAME} --new-image $CONTAINER_PATH
          git commit -m "Updated ${REPO_NAME} in environment $ENVIRONMENT with build type ${{env.buildtype}} with container ${CONTAINER_PATH}" -a
          git push
          cd $GITHUB_WORKSPACE

