name: Run db migrations

on:
  workflow_call:
    secrets:
      DB_USER:
        required: true
      DB_PASSWORD:
        required: true
      DB_NAME:
        required: true
      DB_HOST:
        required: true
      ORG_REPO_ROBOT_SECRET:
        required: true

env:
  DB_USER: ${{ secrets.DB_USER }}
  DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
  DB_HOST: ${{ secrets.DB_HOST }}
  DB_NAME: ${{ secrets.DB_NAME }}
  ORG_REPO_ROBOT_SECRET: ${{ secrets.ORG_REPO_ROBOT_SECRET }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          repository: incidentware/db
          ref: main
          path: db
          token: ${{ secrets.ORG_REPO_ROBOT_SECRET }}

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.1'

      - name: Install migrate CLI
        run: go install -tags 'postgres' github.com/golang-migrate/migrate/v4/cmd/migrate@latest

      - name: Run database migrations
        run: |
          cd db
          make migrate-up

