name: Run db migrations

on:
  workflow_call:
    secrets:
      DB_USER:
        required: true
      DB_PASSWORD:
        required: true
      DB_NAME:
        required: true
      DB_HOST:
        required: true

env:
  dbuser: ${{ secrets.DB_USER }}
  dbpassword: ${{ secrets.DB_PASSWORD }}
  dbhost: ${{ secrets.DB_HOST }}
  dbname: ${{ secrets.DB_NAME }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24.1'

      - name: Set environment variables
        run: |
          echo "DATABASE_URL=postgres://${{ secrets.DB_USER }}:${{ secrets.DB_PASSWORD }}@{{ secrets.DB_HOST }}:5432/${{ secrets.DB_NAME }}?sslmode=disable" >> $GITHUB_ENV

      - name: Install migrate CLI
        run: go install -tags 'postgres' github.com/golang-migrate/migrate/v4/cmd/migrate@latest

      - name: Run database migrations
        run: |
          make migrate up

